### ISSUE TITLE
Discussing measures of surface brightness depth and devising completeness estimates with experts

### ISSUE THREAD

**Issue by aemerywatkins** [lsst-uk/sky-estimation-WP3.7#3]

**Comment by tms-epcc** [comment]
As reported at [03/MAR/21 meeting](https://api.media.atlassian.com/file/e66ba4f4-0176-4575-8314-b25672c9972d/binary?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzNDMyZmNkYy1kZTM1LTRmMDktOGNjYy04NTI3NWQyMmJjYWEiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmU2NmJhNGY0LTAxNzYtNDU3NS04MzE0LWIyNTY3MmM5OTcyZCI6WyJyZWFkIl19LCJleHAiOjE2MTQ5NjI1NzEsIm5iZiI6MTYxNDg3OTU5MX0.xIWrbZ_JJllsNOpJiIxOaCRPfe0M6wkoNlWz6RGdIpA&client=3432fcdc-de35-4f09-8ccc-85275d22bcaa&name=LUSC-WP3.7-Planning-2021-03-04.txt),  this ticket contributed to deliverables D3.7.1 and D3.7.2. D3.7.1 has been approved and is published.  D3.7.2 is now under revision following review, hence this ticket can be closed.
