### ISSUE TITLE
Begin paper draft

### ISSUE THREAD

**Issue by aemerywatkins** [lsst-uk/sky-estimation-WP3.7#6]
Paper will likely concern the results of the source injection, as well as requirements for mitigation of any effects the current sky subtraction has on LSB features.

**Comment by tms-epcc** [comment]
As reported at [03/MAR/21](https://api.media.atlassian.com/file/e66ba4f4-0176-4575-8314-b25672c9972d/binary?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzNDMyZmNkYy1kZTM1LTRmMDktOGNjYy04NTI3NWQyMmJjYWEiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmU2NmJhNGY0LTAxNzYtNDU3NS04MzE0LWIyNTY3MmM5OTcyZCI6WyJyZWFkIl19LCJleHAiOjE2MTQ5NjI1NzEsIm5iZiI6MTYxNDg3OTU5MX0.xIWrbZ_JJllsNOpJiIxOaCRPfe0M6wkoNlWz6RGdIpA&client=3432fcdc-de35-4f09-8ccc-85275d22bcaa&name=LUSC-WP3.7-Planning-2021-03-04.txt), it was that this  can be closed. This concerned a paper being written about alternative sky subtraction software that was written while waiting for the outcome of the DM tests.
